/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* src = "modoContador.v:2" *)
module MODO(clk, rst, enable, modo, d, q, rco);
  (* src = "modoContador.v:15" *)
  wire [3:0] _00_;
  (* src = "modoContador.v:15" *)
  wire _01_;
  (* src = "modoContador.v:30" *)
  wire [3:0] _02_;
  (* src = "modoContador.v:30" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  (* src = "modoContador.v:9" *)
  input clk;
  (* src = "modoContador.v:11" *)
  input [3:0] d;
  (* src = "modoContador.v:9" *)
  input enable;
  (* src = "modoContador.v:10" *)
  input [1:0] modo;
  (* src = "modoContador.v:12" *)
  output [3:0] q;
  (* src = "modoContador.v:13" *)
  output rco;
  (* src = "modoContador.v:9" *)
  input rst;
  NOT _43_ (
    .A(q[3]),
    .Y(_05_)
  );
  NOT _44_ (
    .A(modo[0]),
    .Y(_06_)
  );
  NOT _45_ (
    .A(rco),
    .Y(_07_)
  );
  NOT _46_ (
    .A(enable),
    .Y(_08_)
  );
  NOT _47_ (
    .A(rst),
    .Y(_09_)
  );
  NOT _48_ (
    .A(clk),
    .Y(_10_)
  );
  NOT _49_ (
    .A(d[0]),
    .Y(_11_)
  );
  NOT _50_ (
    .A(d[1]),
    .Y(_12_)
  );
  NAND _51_ (
    .A(modo[0]),
    .B(modo[1]),
    .Y(_13_)
  );
  NOT _52_ (
    .A(_13_),
    .Y(_14_)
  );
  NOR _53_ (
    .A(modo[0]),
    .B(modo[1]),
    .Y(_15_)
  );
  NOR _54_ (
    .A(_14_),
    .B(_15_),
    .Y(_00_[3])
  );
  NAND _55_ (
    .A(_05_),
    .B(_00_[3]),
    .Y(_16_)
  );
  NOR _56_ (
    .A(_10_),
    .B(_13_),
    .Y(_01_)
  );
  NAND _57_ (
    .A(q[3]),
    .B(_15_),
    .Y(_17_)
  );
  NOT _58_ (
    .A(_17_),
    .Y(_18_)
  );
  NOR _59_ (
    .A(_01_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _60_ (
    .A(_16_),
    .B(_19_),
    .Y(_20_)
  );
  NOR _61_ (
    .A(_08_),
    .B(rst),
    .Y(_21_)
  );
  NAND _62_ (
    .A(enable),
    .B(_09_),
    .Y(_22_)
  );
  NAND _63_ (
    .A(_20_),
    .B(_21_),
    .Y(_23_)
  );
  NOR _64_ (
    .A(_08_),
    .B(_00_[3]),
    .Y(_24_)
  );
  NOR _65_ (
    .A(_07_),
    .B(_24_),
    .Y(_25_)
  );
  NAND _66_ (
    .A(_09_),
    .B(_25_),
    .Y(_26_)
  );
  NAND _67_ (
    .A(_23_),
    .B(_26_),
    .Y(_03_)
  );
  NOR _68_ (
    .A(_11_),
    .B(_13_),
    .Y(_27_)
  );
  NOR _69_ (
    .A(q[3]),
    .B(modo[1]),
    .Y(_28_)
  );
  NOR _70_ (
    .A(_27_),
    .B(_28_),
    .Y(_29_)
  );
  NOR _71_ (
    .A(_22_),
    .B(_29_),
    .Y(_30_)
  );
  NOT _72_ (
    .A(_30_),
    .Y(_31_)
  );
  NAND _73_ (
    .A(q[3]),
    .B(_22_),
    .Y(_32_)
  );
  NAND _74_ (
    .A(_31_),
    .B(_32_),
    .Y(_02_[0])
  );
  NAND _75_ (
    .A(modo[1]),
    .B(_12_),
    .Y(_33_)
  );
  NOR _76_ (
    .A(_06_),
    .B(_22_),
    .Y(_34_)
  );
  NAND _77_ (
    .A(_33_),
    .B(_34_),
    .Y(_35_)
  );
  NAND _78_ (
    .A(_32_),
    .B(_35_),
    .Y(_02_[1])
  );
  NOR _79_ (
    .A(d[2]),
    .B(_13_),
    .Y(_36_)
  );
  NOT _80_ (
    .A(_36_),
    .Y(_37_)
  );
  NOR _81_ (
    .A(_15_),
    .B(_22_),
    .Y(_38_)
  );
  NAND _82_ (
    .A(_37_),
    .B(_38_),
    .Y(_39_)
  );
  NAND _83_ (
    .A(_32_),
    .B(_39_),
    .Y(_02_[2])
  );
  NOR _84_ (
    .A(d[3]),
    .B(_13_),
    .Y(_40_)
  );
  NOT _85_ (
    .A(_40_),
    .Y(_41_)
  );
  NAND _86_ (
    .A(_38_),
    .B(_41_),
    .Y(_42_)
  );
  NAND _87_ (
    .A(_32_),
    .B(_42_),
    .Y(_02_[3])
  );
  BUF _88_ (
    .A(rst),
    .Y(_04_)
  );
  (* src = "modoContador.v:30" *)
  DFF _89_ (
    .C(clk),
    .D(_02_[0]),
    .Q(q[3])
  );
  (* src = "modoContador.v:30" *)
  DFF _90_ (
    .C(clk),
    .D(_02_[1]),
    .Q(q[3])
  );
  (* src = "modoContador.v:30" *)
  DFF _91_ (
    .C(clk),
    .D(_02_[2]),
    .Q(q[3])
  );
  (* src = "modoContador.v:30" *)
  DFF _92_ (
    .C(clk),
    .D(_02_[3]),
    .Q(q[3])
  );
  (* src = "modoContador.v:30" *)
  DFF _93_ (
    .C(clk),
    .D(_03_),
    .Q(rco)
  );
  (* src = "modoContador.v:15" *)
  \$_DLATCH_P_  _94_ (
    .D(_00_[3]),
    .E(_04_),
    .Q(q[3])
  );
  (* src = "modoContador.v:15" *)
  \$_DLATCH_P_  _95_ (
    .D(_01_),
    .E(rst),
    .Q(rco)
  );
  assign q[2:0] = { q[3], q[3], q[3] };
endmodule

(* top =  1  *)
(* src = "modo16bits.v:3" *)
module MODO_16bit(clk, rst, enable, modo, d, q, rco);
  (* src = "modo16bits.v:10" *)
  input clk;
  (* src = "modo16bits.v:12" *)
  input [15:0] d;
  (* src = "modo16bits.v:10" *)
  input enable;
  (* src = "modo16bits.v:11" *)
  input [1:0] modo;
  (* src = "modo16bits.v:13" *)
  output [15:0] q;
  (* src = "modo16bits.v:14" *)
  output rco;
  (* src = "modo16bits.v:16" *)
  wire rco_1;
  (* src = "modo16bits.v:16" *)
  wire rco_2;
  (* src = "modo16bits.v:16" *)
  wire rco_3;
  (* src = "modo16bits.v:10" *)
  input rst;
  (* src = "modo16bits.v:18" *)
  MODO M0 (
    .clk(clk),
    .d(d[3:0]),
    .enable(enable),
    .modo(modo),
    .q(q[3:0]),
    .rco(rco_1),
    .rst(rst)
  );
  (* src = "modo16bits.v:27" *)
  MODO M1 (
    .clk(rco_1),
    .d(d[7:4]),
    .enable(enable),
    .modo(modo),
    .q(q[7:4]),
    .rco(rco_2),
    .rst(rst)
  );
  (* src = "modo16bits.v:36" *)
  MODO M2 (
    .clk(rco_2),
    .d(d[11:8]),
    .enable(enable),
    .modo(modo),
    .q(q[11:8]),
    .rco(rco_3),
    .rst(rst)
  );
  (* src = "modo16bits.v:45" *)
  MODO M3 (
    .clk(rco_3),
    .d(d[15:12]),
    .enable(enable),
    .modo(modo),
    .q(q[15:12]),
    .rco(rco),
    .rst(rst)
  );
endmodule
